version: '3.1'

services:

  web:
    build: ./web-application
    ports:
      - 8899:8899
    networks:
      oleg_university:
        ipv4_address: 192.168.5.11

  rest:
    build: ./rest-application
    ports:
      - 8898:8898
    networks:
      oleg_university:
        ipv4_address: 192.168.5.10

networks:
  oleg_university:
    external: true
